using Icbank.Platform.Application.Common.Interfaces;
using Icbank.Platform.Application.Common.Models;
using Icbank.Platform.Application.Storage;
using Icbank.Platform.Domain.Shorfah;
using MediatR;

namespace Icbank.Platform.Application.Shorfah.Commands;

/// <summary>
/// Handles <see cref="UploadShorfahSectionMediaCommand"/>. Ports <c>shorfah.ts:559-597</c>:
/// contribute/review/approve/admin may upload; 8MB cap preserved verbatim; the object path is
/// always server-generated by <see cref="IObjectStorageWriter"/> (SEC-17 class: never derived
/// from a client-supplied filename).
/// </summary>
public sealed class UploadShorfahSectionMediaCommandHandler : IRequestHandler<UploadShorfahSectionMediaCommand, Result<ShorfahSectionMediaDto>>
{
    /// <summary>The sentinel error returned when the caller lacks any qualifying tier.</summary>
    public const string ForbiddenError = "غير مصرح";

    /// <summary>The sentinel error returned when the decoded payload exceeds the size cap.</summary>
    public const string TooLargeError = "الملف كبير جداً (الحد 8 ميجابايت)";

    /// <summary>The sentinel error returned when the base64 payload cannot be decoded.</summary>
    public const string InvalidBase64Error = "base64 غير صالح";

    private const long MaxBytes = 8 * 1024 * 1024;
    private const string FolderPrefix = "shorfah/media/";
    private const string DefaultContentType = "image/png";

    private readonly IApplicationDbContext _dbContext;
    private readonly IShorfahSectionAccessService _accessService;
    private readonly IObjectStorageWriter _storageWriter;
    private readonly IAuditLogService _auditLogService;

    /// <summary>Initializes a new instance of the <see cref="UploadShorfahSectionMediaCommandHandler"/> class.</summary>
    /// <param name="dbContext">The persistence port.</param>
    /// <param name="accessService">The per-section permission-tier port.</param>
    /// <param name="storageWriter">The object-storage write port.</param>
    /// <param name="auditLogService">The privileged-action audit log port.</param>
    public UploadShorfahSectionMediaCommandHandler(
        IApplicationDbContext dbContext, IShorfahSectionAccessService accessService, IObjectStorageWriter storageWriter, IAuditLogService auditLogService)
    {
        _dbContext = dbContext;
        _accessService = accessService;
        _storageWriter = storageWriter;
        _auditLogService = auditLogService;
    }

    /// <inheritdoc />
    public async Task<Result<ShorfahSectionMediaDto>> Handle(UploadShorfahSectionMediaCommand request, CancellationToken cancellationToken)
    {
        var allowed = await IsAllowedAsync(request, cancellationToken);
        if (!allowed)
        {
            return Result<ShorfahSectionMediaDto>.Failure(ForbiddenError);
        }

        Result<byte[]> decoded = DecodeAndValidate(request.DataBase64);
        if (!decoded.IsSuccess)
        {
            return Result<ShorfahSectionMediaDto>.Failure(decoded.Error!);
        }

        ShorfahSectionMedia media = await SaveMediaAsync(request, decoded.Value!, cancellationToken);

        return Result<ShorfahSectionMediaDto>.Success(
            new ShorfahSectionMediaDto(media.Id, media.SectionId, media.MediaUrl, media.MediaType.ToString(), media.CaptionAr, media.DisplayOrder));
    }

    private static Result<byte[]> DecodeAndValidate(string dataBase64)
    {
        byte[] bytes;
        try
        {
            var base64 = ExtractBase64(dataBase64);
            bytes = Convert.FromBase64String(base64);
        }
        catch (FormatException)
        {
            return Result<byte[]>.Failure(InvalidBase64Error);
        }

        return bytes.LongLength > MaxBytes ? Result<byte[]>.Failure(TooLargeError) : Result<byte[]>.Success(bytes);
    }

    private static string ExtractBase64(string dataBase64) =>
        dataBase64.Contains(',', StringComparison.Ordinal) ? dataBase64[(dataBase64.IndexOf(',', StringComparison.Ordinal) + 1)..] : dataBase64;

    private async Task<ShorfahSectionMedia> SaveMediaAsync(UploadShorfahSectionMediaCommand request, byte[] bytes, CancellationToken cancellationToken)
    {
        var contentType = string.IsNullOrEmpty(request.ContentType) ? DefaultContentType : request.ContentType;
        var objectPath = await _storageWriter.SaveAsync(FolderPrefix, bytes, contentType, cancellationToken);

        var media = new ShorfahSectionMedia
        {
            SectionId = request.SectionId,
            MediaUrl = objectPath,
            MediaType = contentType.StartsWith("image/", StringComparison.OrdinalIgnoreCase) ? ShorfahMediaType.Image : ShorfahMediaType.File,
            CaptionAr = request.CaptionAr,
            DisplayOrder = request.DisplayOrder ?? 0,
            CreatedBy = ShorfahMappers.IdString(request.ActorUserId),
        };
        _dbContext.Add(media);
        await _dbContext.SaveChangesAsync(cancellationToken);

        await _auditLogService.RecordAsync(
            request.ActorUserId,
            "shorfah_media.upload",
            "ShorfahSectionMedia",
            ShorfahMappers.IdString(media.Id),
            before: null,
            after: new { media.SectionId, media.MediaType },
            cancellationToken);

        return media;
    }

    private async Task<bool> IsAllowedAsync(UploadShorfahSectionMediaCommand request, CancellationToken cancellationToken)
    {
        if (await _accessService.IsAdminAsync(request.ActorUserId, cancellationToken))
        {
            return true;
        }

        return await _accessService.CanAccessSectionAsync(request.ActorUserId, request.SectionId, ShorfahSectionAccessTier.Contribute, cancellationToken)
            || await _accessService.CanAccessSectionAsync(request.ActorUserId, request.SectionId, ShorfahSectionAccessTier.Review, cancellationToken)
            || await _accessService.CanAccessSectionAsync(request.ActorUserId, request.SectionId, ShorfahSectionAccessTier.Approve, cancellationToken);
    }
}
