namespace Icbank.Platform.Application.Storage;

/// <summary>
/// Port for persisting server-generated bytes (composed designs, AI-generated backgrounds,
/// rendered icon-event posters) directly to object storage, as opposed to
/// <see cref="IObjectUploadUrlIssuer"/>'s client-PUTs-directly presigned-URL flow. Mirrors the
/// Node source's <c>ObjectStorageService.saveComposedDesign()</c> /
/// <c>saveGeneratedBackground()</c> methods (BUSINESS-RULES.md §7, §12).
/// </summary>
public interface IObjectStorageWriter
{
    /// <summary>Persists the given bytes under the given folder prefix and returns the canonical object path.</summary>
    /// <param name="folderPrefix">The storage folder prefix, e.g. <c>designs/generated/</c>.</param>
    /// <param name="content">The raw bytes to persist.</param>
    /// <param name="contentType">The MIME content type.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The canonical object path clients can later read back via <see cref="IObjectStorageReader"/>.</returns>
    Task<string> SaveAsync(string folderPrefix, byte[] content, string contentType, CancellationToken cancellationToken);
}
