// Generate a TypeScript module that embeds Frutiger fonts as data URIs
const fs = require('fs');
const path = require('path');

const fontDir = path.join(__dirname, '..', 'public', 'fonts');
const outFile = path.join(__dirname, '..', 'src', 'composer', 'frutiger-fonts.ts');

function toDataUri(file) {
  const buf = fs.readFileSync(path.join(fontDir, file));
  const b64 = buf.toString('base64');
  return `data:font/ttf;base64,${b64}`;
}

const light = toDataUri('Frutiger-LT-Arabic-45-Light.ttf');
const roman = toDataUri('Frutiger-LT-Arabic-55-Roman.ttf');
const bold = toDataUri('Frutiger-LT-Arabic-65-Bold.ttf');

const css = `@font-face{font-family:'Frutiger LT Arabic';src:url('${light}') format('truetype');font-weight:300;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${roman}') format('truetype');font-weight:400;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${roman}') format('truetype');font-weight:500;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${bold}') format('truetype');font-weight:600;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${bold}') format('truetype');font-weight:700;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${bold}') format('truetype');font-weight:800;font-style:normal;font-display:block;}
@font-face{font-family:'Frutiger LT Arabic';src:url('${bold}') format('truetype');font-weight:900;font-style:normal;font-display:block;}`;

const ts = `// AUTO-GENERATED by scripts/build-fonts.js — DO NOT EDIT
// Frutiger LT Arabic — GAC official font
export const FRUTIGER_FONT_CSS = ${JSON.stringify(css)};
`;

fs.writeFileSync(outFile, ts);
console.log('wrote', outFile, 'size:', ts.length);
