<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Icbank.Platform.Domain\Icbank.Platform.Domain.csproj" />
    <ProjectReference Include="..\Icbank.Platform.Application\Icbank.Platform.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="HtmlAgilityPack" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Rendering\Fonts\Cairo-Variable.ttf" />
  </ItemGroup>

</Project>
